### ISSUE TITLE
How is this._init = function callled?

### ISSUE THREAD

**Issue by artworkad** [andygup/node-background-processor#2]
Thanks for the awesome snippet, helped me a lot. I have a question, how is 

```
this._init = function
```

called? You have the method declaration but you never called the method.

**Comment by andygup** [comment]
@ArtworkAD That function is called a Self Invoking Function. The following syntax is what triggers the function to automatically run:

`.bind(this)()`

This is just shorthand for running this._init(); from somewhere else in the library.
